pipeline {
    agent none
    stages {
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-windows:python2'
                    args '-u root:sudo'
                }
            }
            steps {
                sh 'python -m pip install --upgrade pip && pip install -r requirements.txt && pyinstaller --onefile sources/Personnel.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/Personnel.exe'
                }
            }
        }
    }
}